using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace DevExp_LinqToSql
{
    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            //treeList1.DataSource = new System.ComponentModel.BindingList<DevExp_LinqToSql.NTSDataSet>() /* TODO: Assign the real data here.*/;
            // This line of code is generated by Data Source Configuration Wizard
            alarmTableBindingSource.DataSource = new DevExp_LinqToSql.DataClasses1DataContext().AlarmTable;
        }
    }
}
