<?xml version="1.0" encoding="utf-8"?><Database Name="NTS" Class="ntsDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=NEWBIGWATER\SQLEXPRESS;Initial Catalog=NTS;User ID=sa" SettingsObjectName="AlarmHistory.Properties.Settings" SettingsPropertyName="NTSConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.AlarmTable" Member="AlarmTable">
    <Type Name="AlarmTable">
      <Column Name="ReceivedTime" Type="System.DateTime" DbType="DateTime NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AlarmCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AlarmHexCode" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="AlarmHappen" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Category" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Unit" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AlarmTextKorean" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="AlarmTextChinese" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TM1_SENSOR1" Member="TM1_SENSOR1">
    <Type Name="TM1_SENSOR1">
      <Column Name="ReceivedTime" Type="System.DateTime" DbType="DateTime NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="O2PPM" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="O2Percent" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="H2PPM" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="Pressure" Type="System.Single" DbType="Real" CanBeNull="true" />
    </Type>
  </Table>
</Database>