#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExpress
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="NTS")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 확장성 메서드 정의
    partial void OnCreated();
    partial void InsertTM1_BUFFER(TM1_BUFFER instance);
    partial void UpdateTM1_BUFFER(TM1_BUFFER instance);
    partial void DeleteTM1_BUFFER(TM1_BUFFER instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::DevExpress.Properties.Settings.Default.NTSConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TM1_BUFFER> TM1_BUFFER
		{
			get
			{
				return this.GetTable<TM1_BUFFER>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TM1_BUFFER")]
	public partial class TM1_BUFFER : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.DateTime _ReceivedTime;
		
		private System.Nullable<float> _O2PPM;
		
		private System.Nullable<float> _O2Percent;
		
		private System.Nullable<float> _H2PPM;
		
		private System.Nullable<float> _Pressure;
		
    #region 확장성 메서드 정의
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnReceivedTimeChanging(System.DateTime value);
    partial void OnReceivedTimeChanged();
    partial void OnO2PPMChanging(System.Nullable<float> value);
    partial void OnO2PPMChanged();
    partial void OnO2PercentChanging(System.Nullable<float> value);
    partial void OnO2PercentChanged();
    partial void OnH2PPMChanging(System.Nullable<float> value);
    partial void OnH2PPMChanged();
    partial void OnPressureChanging(System.Nullable<float> value);
    partial void OnPressureChanged();
    #endregion
		
		public TM1_BUFFER()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReceivedTime", DbType="DateTime NOT NULL", IsPrimaryKey=true)]
		public System.DateTime ReceivedTime
		{
			get
			{
				return this._ReceivedTime;
			}
			set
			{
				if ((this._ReceivedTime != value))
				{
					this.OnReceivedTimeChanging(value);
					this.SendPropertyChanging();
					this._ReceivedTime = value;
					this.SendPropertyChanged("ReceivedTime");
					this.OnReceivedTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O2PPM", DbType="Real")]
		public System.Nullable<float> O2PPM
		{
			get
			{
				return this._O2PPM;
			}
			set
			{
				if ((this._O2PPM != value))
				{
					this.OnO2PPMChanging(value);
					this.SendPropertyChanging();
					this._O2PPM = value;
					this.SendPropertyChanged("O2PPM");
					this.OnO2PPMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O2Percent", DbType="Real")]
		public System.Nullable<float> O2Percent
		{
			get
			{
				return this._O2Percent;
			}
			set
			{
				if ((this._O2Percent != value))
				{
					this.OnO2PercentChanging(value);
					this.SendPropertyChanging();
					this._O2Percent = value;
					this.SendPropertyChanged("O2Percent");
					this.OnO2PercentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_H2PPM", DbType="Real")]
		public System.Nullable<float> H2PPM
		{
			get
			{
				return this._H2PPM;
			}
			set
			{
				if ((this._H2PPM != value))
				{
					this.OnH2PPMChanging(value);
					this.SendPropertyChanging();
					this._H2PPM = value;
					this.SendPropertyChanged("H2PPM");
					this.OnH2PPMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pressure", DbType="Real")]
		public System.Nullable<float> Pressure
		{
			get
			{
				return this._Pressure;
			}
			set
			{
				if ((this._Pressure != value))
				{
					this.OnPressureChanging(value);
					this.SendPropertyChanging();
					this._Pressure = value;
					this.SendPropertyChanged("Pressure");
					this.OnPressureChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
