using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;

namespace DevExpress
{
    public partial class XtraForm1 : DevExpress.XtraEditors.XtraForm
    {
        private  Sample  aaaa = new Sample();
        public XtraForm1()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            tM1_BUFFERBindingSource.DataSource = new DevExpress.DataClasses1DataContext().TM1_BUFFER;
        }

        private void simpleButton1_Click(object sender, EventArgs e)
        {
            aaaa.Married = false;
            aaaa.Name = "aaa";
            aaaa.Old = 33;

            aaaa.Phone = "121313";
            sampleBindingSource.Add(aaaa);


        }

        private void button1_Click(object sender, EventArgs e)
        {
            aaaa._phone = "222222222";
            PhoneTextEdit.Update();
        }
    }
}